/*
Shortcut API

Shortcut API

API version: 3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the MilestoneStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MilestoneStats{}

// MilestoneStats A group of calculated values for this Milestone.
type MilestoneStats struct {
	// The average cycle time (in seconds) of completed stories in this Milestone.
	AverageCycleTime *int64 `json:"average_cycle_time,omitempty"`
	// The average lead time (in seconds) of completed stories in this Milestone.
	AverageLeadTime *int64 `json:"average_lead_time,omitempty"`
	// The number of related documents tp this Milestone.
	NumRelatedDocuments int64 `json:"num_related_documents"`
}

// NewMilestoneStats instantiates a new MilestoneStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMilestoneStats(numRelatedDocuments int64) *MilestoneStats {
	this := MilestoneStats{}
	this.NumRelatedDocuments = numRelatedDocuments
	return &this
}

// NewMilestoneStatsWithDefaults instantiates a new MilestoneStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMilestoneStatsWithDefaults() *MilestoneStats {
	this := MilestoneStats{}
	return &this
}

// GetAverageCycleTime returns the AverageCycleTime field value if set, zero value otherwise.
func (o *MilestoneStats) GetAverageCycleTime() int64 {
	if o == nil || IsNil(o.AverageCycleTime) {
		var ret int64
		return ret
	}
	return *o.AverageCycleTime
}

// GetAverageCycleTimeOk returns a tuple with the AverageCycleTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MilestoneStats) GetAverageCycleTimeOk() (*int64, bool) {
	if o == nil || IsNil(o.AverageCycleTime) {
		return nil, false
	}
	return o.AverageCycleTime, true
}

// HasAverageCycleTime returns a boolean if a field has been set.
func (o *MilestoneStats) HasAverageCycleTime() bool {
	if o != nil && !IsNil(o.AverageCycleTime) {
		return true
	}

	return false
}

// SetAverageCycleTime gets a reference to the given int64 and assigns it to the AverageCycleTime field.
func (o *MilestoneStats) SetAverageCycleTime(v int64) {
	o.AverageCycleTime = &v
}

// GetAverageLeadTime returns the AverageLeadTime field value if set, zero value otherwise.
func (o *MilestoneStats) GetAverageLeadTime() int64 {
	if o == nil || IsNil(o.AverageLeadTime) {
		var ret int64
		return ret
	}
	return *o.AverageLeadTime
}

// GetAverageLeadTimeOk returns a tuple with the AverageLeadTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MilestoneStats) GetAverageLeadTimeOk() (*int64, bool) {
	if o == nil || IsNil(o.AverageLeadTime) {
		return nil, false
	}
	return o.AverageLeadTime, true
}

// HasAverageLeadTime returns a boolean if a field has been set.
func (o *MilestoneStats) HasAverageLeadTime() bool {
	if o != nil && !IsNil(o.AverageLeadTime) {
		return true
	}

	return false
}

// SetAverageLeadTime gets a reference to the given int64 and assigns it to the AverageLeadTime field.
func (o *MilestoneStats) SetAverageLeadTime(v int64) {
	o.AverageLeadTime = &v
}

// GetNumRelatedDocuments returns the NumRelatedDocuments field value
func (o *MilestoneStats) GetNumRelatedDocuments() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.NumRelatedDocuments
}

// GetNumRelatedDocumentsOk returns a tuple with the NumRelatedDocuments field value
// and a boolean to check if the value has been set.
func (o *MilestoneStats) GetNumRelatedDocumentsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NumRelatedDocuments, true
}

// SetNumRelatedDocuments sets field value
func (o *MilestoneStats) SetNumRelatedDocuments(v int64) {
	o.NumRelatedDocuments = v
}

func (o MilestoneStats) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MilestoneStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AverageCycleTime) {
		toSerialize["average_cycle_time"] = o.AverageCycleTime
	}
	if !IsNil(o.AverageLeadTime) {
		toSerialize["average_lead_time"] = o.AverageLeadTime
	}
	toSerialize["num_related_documents"] = o.NumRelatedDocuments
	return toSerialize, nil
}

type NullableMilestoneStats struct {
	value *MilestoneStats
	isSet bool
}

func (v NullableMilestoneStats) Get() *MilestoneStats {
	return v.value
}

func (v *NullableMilestoneStats) Set(val *MilestoneStats) {
	v.value = val
	v.isSet = true
}

func (v NullableMilestoneStats) IsSet() bool {
	return v.isSet
}

func (v *NullableMilestoneStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMilestoneStats(val *MilestoneStats) *NullableMilestoneStats {
	return &NullableMilestoneStats{value: val, isSet: true}
}

func (v NullableMilestoneStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMilestoneStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


